--- 
- 
  become: true
  hosts: webservers
  tasks: 
    - name: "Copy jar file"
      copy: 
        dest: /home/petclinic/
        src: /var/lib/jenkins/workspace/ansible-demo/target/spring-petclinic-2.6.0-SNAPSHOT.jar
    - name: "Deploy Jar file"
      shell: "java -jar target/*.jar"
