--- 
- 
  hosts: webservers
  sudo: no
  connection: ssh
  remote_user: ubuntu
  gather_facts: yes
  tasks: 
    - 
      name: "Install packages"
      yum: 
        name: httpd
        state: present
    - 
      name: "Start Apache server"
      service: 
        enabled: true
        name: httpd
        state: started
    - name: "Create jar file"
      shell: "./mvnw package"
    - name: "Copy jar file"
      copy: 
        dest: /home/petclinic/
        src: target/spring-petclinic-2.6.0-SNAPSHOT.jar
    - name: "Deploy Jar file"
      shell: "java -jar target/*.jar"
