---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Copy jar file
      copy:
        src: target/spring-petclinic-2.6.0-SNAPSHOT.jar
        dest: /home/petclinic/
    - name: Deploy Jar file
        shell: "java -jar /home/petclinic/spring-petclinic-2.6.0-SNAPSHOT.jar"

...
