--- 
- 
  become: true
  hosts: webservers
  tasks: 
    - 
      name: "Install packages"
      yum: 
        name: httpd
        state: present
    - 
      name: "Start Apache server"
      service: 
        enabled: true
        name: httpd
        state: started
    - 
      goals: "clean install"
      maven: ~
      pom-file: pom.xml
    - 
      copy: 
        dest: /home/petclinic/
        src: target/spring-petclinic-2.6.0-SNAPSHOT.jar
      name: "Copy jar file"
    - 
      name: "Deploy Jar file"
    - 
      shell: "java -jar target/*.jar"
